[package]
name = "rust_new_project_inside_var_folder"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"

[dev-dependencies]
grcov = "0.8.18"
cargo-tarpaulin = "0.27.1"

[features]
coverage = []
