[package]
name = "rust_new_project_inside_var_folder"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"

[dev-dependencies]
test-case = "3.3.1"
cargo-llvm-cov = "0.5.39"

[lib]
name = "rust_new_project_inside_var_folder"
path = "src/lib.rs"
